var PATCHWORK_APPLICATION           = "APPLICATION_UID";
var PATCHWORK_TOKEN                 = "APPLICATION_TOKEN";
var PATCHWORK_EMAIL_PLATFORM_UID    = "EMAIL_UID";
var PATCHWORK_STRIPE_PLATFORM_UID   = "STRIPE_UID";
var PATCHWORK_BILL_PAY_PLATFORM_UID = "BILLPAY_UID";
