var PATCHWORK_ACCOUNT_ID         = "ACCOUNT_ID";
var PATCHWORK_API_KEY            = "API_KEY";
var PATCHWORK_EMAIL_PLATFORM_ID  = 1;
var PATCHWORK_STRIPE_PLATFORM_ID = 1;
var PATCHWORK_BILL_PAY_PLATFORM_ID = 1;
